// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertMetricSnapshotsParams struct {
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	PostID         *uuid.UUID         `json:"post_id"`
	PlatformPostID string             `json:"platform_post_id"`
	Metric         string             `json:"metric"`
	Value          int64              `json:"value"`
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
}

const latestMetricsForPost = `-- name: LatestMetricsForPost :many
SELECT DISTINCT ON (channel_id, metric)
    channel_id, platform_post_id, metric, value, captured_at
FROM metric_snapshots
WHERE workspace_id = $1 AND post_id = $2
ORDER BY channel_id, metric, captured_at DESC
`

type LatestMetricsForPostParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	PostID      *uuid.UUID `json:"post_id"`
}

type LatestMetricsForPostRow struct {
	ChannelID      uuid.UUID          `json:"channel_id"`
	PlatformPostID string             `json:"platform_post_id"`
	Metric         string             `json:"metric"`
	Value          int64              `json:"value"`
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
}

// The most recent value of every metric for one post, per channel it was
// published to (workspace-scoped).
func (q *Queries) LatestMetricsForPost(ctx context.Context, arg LatestMetricsForPostParams) ([]LatestMetricsForPostRow, error) {
	rows, err := q.db.Query(ctx, latestMetricsForPost, arg.WorkspaceID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestMetricsForPostRow{}
	for rows.Next() {
		var i LatestMetricsForPostRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.PlatformPostID,
			&i.Metric,
			&i.Value,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestMetricsForWorkspace = `-- name: LatestMetricsForWorkspace :many
WITH latest AS (
    SELECT DISTINCT ON (post_id, channel_id, metric)
        post_id, channel_id, platform_post_id, metric, value, captured_at
    FROM metric_snapshots
    WHERE workspace_id = $1 AND post_id IS NOT NULL
    ORDER BY post_id, channel_id, metric, captured_at DESC
),
groups AS (
    SELECT post_id, channel_id, MAX(captured_at) AS latest_at
    FROM latest
    GROUP BY post_id, channel_id
    ORDER BY latest_at DESC
    LIMIT $2
)
SELECT l.post_id, l.channel_id, l.platform_post_id, l.metric, l.value, l.captured_at
FROM latest l
JOIN groups g ON g.post_id = l.post_id AND g.channel_id = l.channel_id
ORDER BY g.latest_at DESC, l.channel_id, l.metric
`

type LatestMetricsForWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
}

type LatestMetricsForWorkspaceRow struct {
	PostID         *uuid.UUID         `json:"post_id"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	PlatformPostID string             `json:"platform_post_id"`
	Metric         string             `json:"metric"`
	Value          int64              `json:"value"`
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
}

// The most recent value of every metric for the N most-recently-active
// (post, channel) pairs in the workspace. The LIMIT is applied in SQL (by
// recency) so a large workspace never materializes its whole history.
func (q *Queries) LatestMetricsForWorkspace(ctx context.Context, arg LatestMetricsForWorkspaceParams) ([]LatestMetricsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, latestMetricsForWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestMetricsForWorkspaceRow{}
	for rows.Next() {
		var i LatestMetricsForWorkspaceRow
		if err := rows.Scan(
			&i.PostID,
			&i.ChannelID,
			&i.PlatformPostID,
			&i.Metric,
			&i.Value,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsDueForMetrics = `-- name: ListPostsDueForMetrics :many
SELECT c.workspace_id, pr.channel_id, pr.post_id, pr.platform_post_id, c.platform
FROM publish_results pr
JOIN channels c ON c.id = pr.channel_id
WHERE pr.published_at > $1
  AND NOT EXISTS (
    SELECT 1 FROM metric_poll_state ps
    WHERE ps.channel_id = pr.channel_id
      AND ps.platform_post_id = pr.platform_post_id
      AND (ps.done OR ps.last_polled_at > $2)
  )
ORDER BY pr.published_at DESC
LIMIT $3
`

type ListPostsDueForMetricsParams struct {
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	LastPolledAt pgtype.Timestamptz `json:"last_polled_at"`
	Limit        int32              `json:"limit"`
}

type ListPostsDueForMetricsRow struct {
	WorkspaceID    uuid.UUID  `json:"workspace_id"`
	ChannelID      uuid.UUID  `json:"channel_id"`
	PostID         *uuid.UUID `json:"post_id"`
	PlatformPostID string     `json:"platform_post_id"`
	Platform       string     `json:"platform"`
}

// Published posts to poll: published within the lookback window and not polled
// since the cutoff (dedup is per (channel, platform post) via poll-state, so a
// collision on platform_post_id across channels can't suppress another's poll,
// and a post marked done is excluded permanently).
func (q *Queries) ListPostsDueForMetrics(ctx context.Context, arg ListPostsDueForMetricsParams) ([]ListPostsDueForMetricsRow, error) {
	rows, err := q.db.Query(ctx, listPostsDueForMetrics, arg.PublishedAt, arg.LastPolledAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsDueForMetricsRow{}
	for rows.Next() {
		var i ListPostsDueForMetricsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.PostID,
			&i.PlatformPostID,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricSeries = `-- name: MetricSeries :many
SELECT value, captured_at
FROM metric_snapshots
WHERE workspace_id = $1 AND post_id = $2 AND channel_id = $3 AND metric = $4
  AND captured_at >= $5 AND captured_at <= $6
ORDER BY captured_at
`

type MetricSeriesParams struct {
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	PostID       *uuid.UUID         `json:"post_id"`
	ChannelID    uuid.UUID          `json:"channel_id"`
	Metric       string             `json:"metric"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
	CapturedAt_2 pgtype.Timestamptz `json:"captured_at_2"`
}

type MetricSeriesRow struct {
	Value      int64              `json:"value"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
}

// The time series of one metric for one post on one channel within a window.
func (q *Queries) MetricSeries(ctx context.Context, arg MetricSeriesParams) ([]MetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, metricSeries,
		arg.WorkspaceID,
		arg.PostID,
		arg.ChannelID,
		arg.Metric,
		arg.CapturedAt,
		arg.CapturedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricSeriesRow{}
	for rows.Next() {
		var i MetricSeriesRow
		if err := rows.Scan(&i.Value, &i.CapturedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSnapshotsBefore = `-- name: PruneSnapshotsBefore :exec
DELETE FROM metric_snapshots WHERE captured_at < $1
`

// Retention: drop snapshots older than the cutoff to bound table growth.
func (q *Queries) PruneSnapshotsBefore(ctx context.Context, capturedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, pruneSnapshotsBefore, capturedAt)
	return err
}

const upsertPollState = `-- name: UpsertPollState :exec
INSERT INTO metric_poll_state (channel_id, platform_post_id, last_polled_at, done)
VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, platform_post_id)
DO UPDATE SET last_polled_at = EXCLUDED.last_polled_at,
              done = metric_poll_state.done OR EXCLUDED.done
`

type UpsertPollStateParams struct {
	ChannelID      uuid.UUID          `json:"channel_id"`
	PlatformPostID string             `json:"platform_post_id"`
	LastPolledAt   pgtype.Timestamptz `json:"last_polled_at"`
	Done           bool               `json:"done"`
}

// Record a poll attempt for a (channel, platform post). done is sticky: once a
// post is gone at the platform it stays done so it's never polled again.
func (q *Queries) UpsertPollState(ctx context.Context, arg UpsertPollStateParams) error {
	_, err := q.db.Exec(ctx, upsertPollState,
		arg.ChannelID,
		arg.PlatformPostID,
		arg.LastPolledAt,
		arg.Done,
	)
	return err
}
