// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (workspace_id, actor_user_id, action, target, metadata, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type InsertAuditLogParams struct {
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	ActorUserID *uuid.UUID `json:"actor_user_id"`
	Action      string     `json:"action"`
	Target      string     `json:"target"`
	Metadata    []byte     `json:"metadata"`
	Ip          string     `json:"ip"`
}

type InsertAuditLogRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.Action,
		arg.Target,
		arg.Metadata,
		arg.Ip,
	)
	var i InsertAuditLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAuditLogByWorkspace = `-- name: ListAuditLogByWorkspace :many
SELECT id, workspace_id, actor_user_id, action, target, metadata, ip, created_at
FROM audit_log
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogByWorkspaceParams struct {
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	Limit       int32      `json:"limit"`
	Offset      int32      `json:"offset"`
}

func (q *Queries) ListAuditLogByWorkspace(ctx context.Context, arg ListAuditLogByWorkspaceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorUserID,
			&i.Action,
			&i.Target,
			&i.Metadata,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
