// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const creditWallet = `-- name: CreditWallet :one
INSERT INTO wallets (workspace_id, balance, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (workspace_id)
DO UPDATE SET balance = wallets.balance + EXCLUDED.balance, updated_at = now()
RETURNING workspace_id, balance, updated_at
`

type CreditWalletParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Balance     int64     `json:"balance"`
}

// Add credits (topup/refund). The wallet row is created if missing.
func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, creditWallet, arg.WorkspaceID, arg.Balance)
	var i Wallet
	err := row.Scan(&i.WorkspaceID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const debitWalletIfEnough = `-- name: DebitWalletIfEnough :one
UPDATE wallets
SET balance = balance - $2, updated_at = now()
WHERE workspace_id = $1 AND balance >= $2
RETURNING workspace_id, balance, updated_at
`

type DebitWalletIfEnoughParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Balance     int64     `json:"balance"`
}

// Atomically deduct; returns no row when funds are insufficient.
func (q *Queries) DebitWalletIfEnough(ctx context.Context, arg DebitWalletIfEnoughParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, debitWalletIfEnough, arg.WorkspaceID, arg.Balance)
	var i Wallet
	err := row.Scan(&i.WorkspaceID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT COALESCE(
    (SELECT balance FROM wallets WHERE workspace_id = $1),
    0
)::BIGINT AS balance
`

func (q *Queries) GetWalletBalance(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletBalance, workspaceID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO wallet_ledger (workspace_id, kind, credits, reference, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, kind, reference) DO NOTHING
RETURNING id, workspace_id, kind, credits, reference, note, created_at
`

type InsertLedgerEntryParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Kind        string    `json:"kind"`
	Credits     int64     `json:"credits"`
	Reference   string    `json:"reference"`
	Note        string    `json:"note"`
}

// Append a ledger entry. ON CONFLICT DO NOTHING + no row returned signals a
// duplicate (webhook retry / double claim) so the caller can skip the credit.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (WalletLedger, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.WorkspaceID,
		arg.Kind,
		arg.Credits,
		arg.Reference,
		arg.Note,
	)
	var i WalletLedger
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Credits,
		&i.Reference,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, workspace_id, kind, credits, reference, note, created_at
FROM wallet_ledger
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]WalletLedger, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletLedger{}
	for rows.Next() {
		var i WalletLedger
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Credits,
			&i.Reference,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWallet = `-- name: UpsertWallet :one
INSERT INTO wallets (workspace_id)
VALUES ($1)
ON CONFLICT (workspace_id) DO UPDATE SET workspace_id = EXCLUDED.workspace_id
RETURNING workspace_id, balance, updated_at
`

// Ensure the workspace has a wallet row and return it.
func (q *Queries) UpsertWallet(ctx context.Context, workspaceID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, upsertWallet, workspaceID)
	var i Wallet
	err := row.Scan(&i.WorkspaceID, &i.Balance, &i.UpdatedAt)
	return i, err
}
