// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channel_grants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteChannelGrantsForUser = `-- name: DeleteChannelGrantsForUser :exec
DELETE FROM channel_grants WHERE workspace_id = $1 AND user_id = $2
`

type DeleteChannelGrantsForUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteChannelGrantsForUser(ctx context.Context, arg DeleteChannelGrantsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteChannelGrantsForUser, arg.WorkspaceID, arg.UserID)
	return err
}

const getMemberChannelRestricted = `-- name: GetMemberChannelRestricted :one
SELECT channel_restricted FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberChannelRestrictedParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberChannelRestricted(ctx context.Context, arg GetMemberChannelRestrictedParams) (bool, error) {
	row := q.db.QueryRow(ctx, getMemberChannelRestricted, arg.WorkspaceID, arg.UserID)
	var channel_restricted bool
	err := row.Scan(&channel_restricted)
	return channel_restricted, err
}

const insertChannelGrant = `-- name: InsertChannelGrant :exec
INSERT INTO channel_grants (workspace_id, channel_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type InsertChannelGrantParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ChannelID   uuid.UUID `json:"channel_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) InsertChannelGrant(ctx context.Context, arg InsertChannelGrantParams) error {
	_, err := q.db.Exec(ctx, insertChannelGrant, arg.WorkspaceID, arg.ChannelID, arg.UserID)
	return err
}

const isChannelPublishAllowed = `-- name: IsChannelPublishAllowed :one
SELECT (NOT m.channel_restricted)
       OR EXISTS (
         SELECT 1 FROM channel_grants g
         WHERE g.channel_id = $1 AND g.user_id = m.user_id
       ) AS allowed
FROM workspace_members m
WHERE m.workspace_id = $2 AND m.user_id = $3
`

type IsChannelPublishAllowedParams struct {
	ChannelID   uuid.UUID `json:"channel_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) IsChannelPublishAllowed(ctx context.Context, arg IsChannelPublishAllowedParams) (*bool, error) {
	row := q.db.QueryRow(ctx, isChannelPublishAllowed, arg.ChannelID, arg.WorkspaceID, arg.UserID)
	var allowed *bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listChannelGrantsForUser = `-- name: ListChannelGrantsForUser :many
SELECT channel_id FROM channel_grants
WHERE workspace_id = $1 AND user_id = $2
`

type ListChannelGrantsForUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) ListChannelGrantsForUser(ctx context.Context, arg ListChannelGrantsForUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listChannelGrantsForUser, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var channel_id uuid.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberChannelRestricted = `-- name: SetMemberChannelRestricted :exec
UPDATE workspace_members SET channel_restricted = $3
WHERE workspace_id = $1 AND user_id = $2
`

type SetMemberChannelRestrictedParams struct {
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	UserID            uuid.UUID `json:"user_id"`
	ChannelRestricted bool      `json:"channel_restricted"`
}

func (q *Queries) SetMemberChannelRestricted(ctx context.Context, arg SetMemberChannelRestrictedParams) error {
	_, err := q.db.Exec(ctx, setMemberChannelRestricted, arg.WorkspaceID, arg.UserID, arg.ChannelRestricted)
	return err
}
