// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (workspace_id, platform, platform_account_id, handle, display_name, connected_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, platform, platform_account_id, handle, display_name, status, connected_by, created_at, updated_at
`

type CreateChannelParams struct {
	WorkspaceID       uuid.UUID  `json:"workspace_id"`
	Platform          string     `json:"platform"`
	PlatformAccountID string     `json:"platform_account_id"`
	Handle            string     `json:"handle"`
	DisplayName       string     `json:"display_name"`
	ConnectedBy       *uuid.UUID `json:"connected_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.WorkspaceID,
		arg.Platform,
		arg.PlatformAccountID,
		arg.Handle,
		arg.DisplayName,
		arg.ConnectedBy,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.PlatformAccountID,
		&i.Handle,
		&i.DisplayName,
		&i.Status,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const deleteChannelCredential = `-- name: DeleteChannelCredential :exec
DELETE FROM channel_credentials
WHERE channel_id = $1
`

func (q *Queries) DeleteChannelCredential(ctx context.Context, channelID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannelCredential, channelID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, workspace_id, platform, platform_account_id, handle, display_name, status, connected_by, created_at, updated_at
FROM channels
WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.PlatformAccountID,
		&i.Handle,
		&i.DisplayName,
		&i.Status,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByAccount = `-- name: GetChannelByAccount :one
SELECT id, workspace_id, platform, platform_account_id, handle, display_name, status, connected_by, created_at, updated_at
FROM channels
WHERE workspace_id = $1 AND platform = $2 AND platform_account_id = $3
`

type GetChannelByAccountParams struct {
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	Platform          string    `json:"platform"`
	PlatformAccountID string    `json:"platform_account_id"`
}

func (q *Queries) GetChannelByAccount(ctx context.Context, arg GetChannelByAccountParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByAccount, arg.WorkspaceID, arg.Platform, arg.PlatformAccountID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.PlatformAccountID,
		&i.Handle,
		&i.DisplayName,
		&i.Status,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelCredential = `-- name: GetChannelCredential :one
SELECT channel_id, encrypted_access_token, encrypted_refresh_token, scopes, expires_at, key_version, created_at, updated_at
FROM channel_credentials
WHERE channel_id = $1
`

func (q *Queries) GetChannelCredential(ctx context.Context, channelID uuid.UUID) (ChannelCredential, error) {
	row := q.db.QueryRow(ctx, getChannelCredential, channelID)
	var i ChannelCredential
	err := row.Scan(
		&i.ChannelID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.Scopes,
		&i.ExpiresAt,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, workspace_id, platform, platform_account_id, handle, display_name, status, connected_by, created_at, updated_at
FROM channels
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListChannels(ctx context.Context, workspaceID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Platform,
			&i.PlatformAccountID,
			&i.Handle,
			&i.DisplayName,
			&i.Status,
			&i.ConnectedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsDueForRefresh = `-- name: ListChannelsDueForRefresh :many
SELECT c.id, c.workspace_id, c.platform, cc.expires_at
FROM channels c
JOIN channel_credentials cc ON cc.channel_id = c.id
WHERE c.status = 'active'
  AND cc.encrypted_refresh_token IS NOT NULL
  AND cc.expires_at IS NOT NULL
  AND cc.expires_at < $1
ORDER BY cc.expires_at
LIMIT $2
`

type ListChannelsDueForRefreshParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

type ListChannelsDueForRefreshRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Platform    string             `json:"platform"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListChannelsDueForRefresh(ctx context.Context, arg ListChannelsDueForRefreshParams) ([]ListChannelsDueForRefreshRow, error) {
	rows, err := q.db.Query(ctx, listChannelsDueForRefresh, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsDueForRefreshRow{}
	for rows.Next() {
		var i ListChannelsDueForRefreshRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Platform,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelIdentity = `-- name: UpdateChannelIdentity :exec
UPDATE channels
SET handle = $2, display_name = $3, updated_at = now()
WHERE id = $1
`

type UpdateChannelIdentityParams struct {
	ID          uuid.UUID `json:"id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) UpdateChannelIdentity(ctx context.Context, arg UpdateChannelIdentityParams) error {
	_, err := q.db.Exec(ctx, updateChannelIdentity, arg.ID, arg.Handle, arg.DisplayName)
	return err
}

const updateChannelStatus = `-- name: UpdateChannelStatus :exec
UPDATE channels
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateChannelStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) error {
	_, err := q.db.Exec(ctx, updateChannelStatus, arg.ID, arg.Status)
	return err
}

const upsertChannelCredential = `-- name: UpsertChannelCredential :exec
INSERT INTO channel_credentials (channel_id, encrypted_access_token, encrypted_refresh_token, scopes, expires_at, key_version)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (channel_id) DO UPDATE
SET encrypted_access_token = EXCLUDED.encrypted_access_token,
    encrypted_refresh_token = EXCLUDED.encrypted_refresh_token,
    scopes = EXCLUDED.scopes,
    expires_at = EXCLUDED.expires_at,
    key_version = EXCLUDED.key_version,
    updated_at = now()
`

type UpsertChannelCredentialParams struct {
	ChannelID             uuid.UUID          `json:"channel_id"`
	EncryptedAccessToken  []byte             `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte             `json:"encrypted_refresh_token"`
	Scopes                []string           `json:"scopes"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	KeyVersion            int32              `json:"key_version"`
}

func (q *Queries) UpsertChannelCredential(ctx context.Context, arg UpsertChannelCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertChannelCredential,
		arg.ChannelID,
		arg.EncryptedAccessToken,
		arg.EncryptedRefreshToken,
		arg.Scopes,
		arg.ExpiresAt,
		arg.KeyVersion,
	)
	return err
}
