// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertMetricSnapshots implements pgx.CopyFromSource.
type iteratorForInsertMetricSnapshots struct {
	rows                 []InsertMetricSnapshotsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertMetricSnapshots) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertMetricSnapshots) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].WorkspaceID,
		r.rows[0].ChannelID,
		r.rows[0].PostID,
		r.rows[0].PlatformPostID,
		r.rows[0].Metric,
		r.rows[0].Value,
		r.rows[0].CapturedAt,
	}, nil
}

func (r iteratorForInsertMetricSnapshots) Err() error {
	return nil
}

// Batched insert of all metrics for one poll (atomic, single round-trip).
func (q *Queries) InsertMetricSnapshots(ctx context.Context, arg []InsertMetricSnapshotsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"metric_snapshots"}, []string{"workspace_id", "channel_id", "post_id", "platform_post_id", "metric", "value", "captured_at"}, &iteratorForInsertMetricSnapshots{rows: arg})
}
