// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: integrations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getWorkspaceIntegration = `-- name: GetWorkspaceIntegration :one
SELECT workspace_id, provider, enabled, auto_apply, credentials, created_at, updated_at
FROM workspace_integrations
WHERE workspace_id = $1 AND provider = $2
`

type GetWorkspaceIntegrationParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Provider    string    `json:"provider"`
}

func (q *Queries) GetWorkspaceIntegration(ctx context.Context, arg GetWorkspaceIntegrationParams) (WorkspaceIntegration, error) {
	row := q.db.QueryRow(ctx, getWorkspaceIntegration, arg.WorkspaceID, arg.Provider)
	var i WorkspaceIntegration
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.Enabled,
		&i.AutoApply,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceIntegrations = `-- name: ListWorkspaceIntegrations :many
SELECT workspace_id, provider, enabled, auto_apply, credentials, created_at, updated_at
FROM workspace_integrations
WHERE workspace_id = $1
ORDER BY provider
`

func (q *Queries) ListWorkspaceIntegrations(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceIntegration, error) {
	rows, err := q.db.Query(ctx, listWorkspaceIntegrations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceIntegration{}
	for rows.Next() {
		var i WorkspaceIntegration
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Provider,
			&i.Enabled,
			&i.AutoApply,
			&i.Credentials,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspaceIntegration = `-- name: UpsertWorkspaceIntegration :one
INSERT INTO workspace_integrations (workspace_id, provider, enabled, auto_apply, credentials, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (workspace_id, provider)
DO UPDATE SET enabled = EXCLUDED.enabled, auto_apply = EXCLUDED.auto_apply,
              credentials = COALESCE(EXCLUDED.credentials, workspace_integrations.credentials),
              updated_at = now()
RETURNING workspace_id, provider, enabled, auto_apply, credentials, created_at, updated_at
`

type UpsertWorkspaceIntegrationParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Provider    string    `json:"provider"`
	Enabled     bool      `json:"enabled"`
	AutoApply   bool      `json:"auto_apply"`
	Credentials []byte    `json:"credentials"`
}

func (q *Queries) UpsertWorkspaceIntegration(ctx context.Context, arg UpsertWorkspaceIntegrationParams) (WorkspaceIntegration, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceIntegration,
		arg.WorkspaceID,
		arg.Provider,
		arg.Enabled,
		arg.AutoApply,
		arg.Credentials,
	)
	var i WorkspaceIntegration
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.Enabled,
		&i.AutoApply,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
