// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (workspace_id, kind, storage_key, mime, width, height, duration_ms, bytes, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, kind, storage_key, mime, width, height, duration_ms, bytes, status, created_at
`

type CreateMediaAssetParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Kind        string    `json:"kind"`
	StorageKey  string    `json:"storage_key"`
	Mime        string    `json:"mime"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	DurationMs  int32     `json:"duration_ms"`
	Bytes       int64     `json:"bytes"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.WorkspaceID,
		arg.Kind,
		arg.StorageKey,
		arg.Mime,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Bytes,
		arg.Status,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Bytes,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaAsset = `-- name: DeleteMediaAsset :exec
DELETE FROM media_assets
WHERE id = $1
`

func (q *Queries) DeleteMediaAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaAsset, id)
	return err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, workspace_id, kind, storage_key, mime, width, height, duration_ms, bytes, status, created_at
FROM media_assets
WHERE id = $1
`

func (q *Queries) GetMediaAsset(ctx context.Context, id uuid.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Bytes,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT id, workspace_id, kind, storage_key, mime, width, height, duration_ms, bytes, status, created_at
FROM media_assets
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMediaAssetsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListMediaAssets(ctx context.Context, arg ListMediaAssetsParams) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssets, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.StorageKey,
			&i.Mime,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Bytes,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceForUpdate = `-- name: LockWorkspaceForUpdate :exec
SELECT id FROM workspaces WHERE id = $1 FOR UPDATE
`

// Row-locks the workspace so a quota check + media insert is serialized against
// concurrent uploads in the same workspace (prevents TOCTOU quota overshoot).
func (q *Queries) LockWorkspaceForUpdate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceForUpdate, id)
	return err
}

const sumMediaBytesForWorkspace = `-- name: SumMediaBytesForWorkspace :one
SELECT COALESCE(SUM(bytes), 0)::BIGINT AS total
FROM media_assets
WHERE workspace_id = $1
`

func (q *Queries) SumMediaBytesForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumMediaBytesForWorkspace, workspaceID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
