// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (workspace_id, author_user_id, status)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, author_user_id, status, created_at, updated_at
`

type CreatePostParams struct {
	WorkspaceID  uuid.UUID  `json:"workspace_id"`
	AuthorUserID *uuid.UUID `json:"author_user_id"`
	Status       string     `json:"status"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.WorkspaceID, arg.AuthorUserID, arg.Status)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPostVariant = `-- name: CreatePostVariant :one
INSERT INTO post_variants (post_id, channel_id, body, media_refs, platform_options)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, post_id, channel_id, body, media_refs, platform_options, created_at, updated_at
`

type CreatePostVariantParams struct {
	PostID          uuid.UUID `json:"post_id"`
	ChannelID       uuid.UUID `json:"channel_id"`
	Body            string    `json:"body"`
	MediaRefs       []byte    `json:"media_refs"`
	PlatformOptions []byte    `json:"platform_options"`
}

func (q *Queries) CreatePostVariant(ctx context.Context, arg CreatePostVariantParams) (PostVariant, error) {
	row := q.db.QueryRow(ctx, createPostVariant,
		arg.PostID,
		arg.ChannelID,
		arg.Body,
		arg.MediaRefs,
		arg.PlatformOptions,
	)
	var i PostVariant
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChannelID,
		&i.Body,
		&i.MediaRefs,
		&i.PlatformOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostVariant = `-- name: DeletePostVariant :exec
DELETE FROM post_variants
WHERE id = $1
`

func (q *Queries) DeletePostVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePostVariant, id)
	return err
}

const deleteVariantsForPost = `-- name: DeleteVariantsForPost :exec
DELETE FROM post_variants
WHERE post_id = $1
`

func (q *Queries) DeleteVariantsForPost(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantsForPost, postID)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, workspace_id, author_user_id, status, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostVariant = `-- name: GetPostVariant :one
SELECT id, post_id, channel_id, body, media_refs, platform_options, created_at, updated_at
FROM post_variants
WHERE id = $1
`

func (q *Queries) GetPostVariant(ctx context.Context, id uuid.UUID) (PostVariant, error) {
	row := q.db.QueryRow(ctx, getPostVariant, id)
	var i PostVariant
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChannelID,
		&i.Body,
		&i.MediaRefs,
		&i.PlatformOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByPostChannel = `-- name: GetVariantByPostChannel :one
SELECT id, post_id, channel_id, body, media_refs, platform_options, created_at, updated_at
FROM post_variants
WHERE post_id = $1 AND channel_id = $2
`

type GetVariantByPostChannelParams struct {
	PostID    uuid.UUID `json:"post_id"`
	ChannelID uuid.UUID `json:"channel_id"`
}

func (q *Queries) GetVariantByPostChannel(ctx context.Context, arg GetVariantByPostChannelParams) (PostVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByPostChannel, arg.PostID, arg.ChannelID)
	var i PostVariant
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChannelID,
		&i.Body,
		&i.MediaRefs,
		&i.PlatformOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostsByWorkspace = `-- name: ListPostsByWorkspace :many
SELECT id, workspace_id, author_user_id, status, created_at, updated_at
FROM posts
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListPostsByWorkspace(ctx context.Context, arg ListPostsByWorkspaceParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AuthorUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByPost = `-- name: ListVariantsByPost :many
SELECT id, post_id, channel_id, body, media_refs, platform_options, created_at, updated_at
FROM post_variants
WHERE post_id = $1
ORDER BY created_at
`

func (q *Queries) ListVariantsByPost(ctx context.Context, postID uuid.UUID) ([]PostVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostVariant{}
	for rows.Next() {
		var i PostVariant
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChannelID,
			&i.Body,
			&i.MediaRefs,
			&i.PlatformOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPost = `-- name: TouchPost :exec
UPDATE posts
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchPost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPost, id)
	return err
}

const updatePostStatus = `-- name: UpdatePostStatus :exec
UPDATE posts
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdatePostStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) error {
	_, err := q.db.Exec(ctx, updatePostStatus, arg.ID, arg.Status)
	return err
}

const updatePostVariant = `-- name: UpdatePostVariant :one
UPDATE post_variants
SET body = $2, media_refs = $3, platform_options = $4, updated_at = now()
WHERE id = $1
RETURNING id, post_id, channel_id, body, media_refs, platform_options, created_at, updated_at
`

type UpdatePostVariantParams struct {
	ID              uuid.UUID `json:"id"`
	Body            string    `json:"body"`
	MediaRefs       []byte    `json:"media_refs"`
	PlatformOptions []byte    `json:"platform_options"`
}

func (q *Queries) UpdatePostVariant(ctx context.Context, arg UpdatePostVariantParams) (PostVariant, error) {
	row := q.db.QueryRow(ctx, updatePostVariant,
		arg.ID,
		arg.Body,
		arg.MediaRefs,
		arg.PlatformOptions,
	)
	var i PostVariant
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChannelID,
		&i.Body,
		&i.MediaRefs,
		&i.PlatformOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
