// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: publish.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getPublishResultByKey = `-- name: GetPublishResultByKey :one
SELECT id, channel_id, post_id, idempotency_key, platform_post_id, raw_response, published_at
FROM publish_results
WHERE idempotency_key = $1
`

func (q *Queries) GetPublishResultByKey(ctx context.Context, idempotencyKey string) (PublishResult, error) {
	row := q.db.QueryRow(ctx, getPublishResultByKey, idempotencyKey)
	var i PublishResult
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PostID,
		&i.IdempotencyKey,
		&i.PlatformPostID,
		&i.RawResponse,
		&i.PublishedAt,
	)
	return i, err
}

const insertPublishResult = `-- name: InsertPublishResult :one
INSERT INTO publish_results (channel_id, idempotency_key, platform_post_id, raw_response)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, post_id, idempotency_key, platform_post_id, raw_response, published_at
`

type InsertPublishResultParams struct {
	ChannelID      uuid.UUID `json:"channel_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	PlatformPostID string    `json:"platform_post_id"`
	RawResponse    []byte    `json:"raw_response"`
}

func (q *Queries) InsertPublishResult(ctx context.Context, arg InsertPublishResultParams) (PublishResult, error) {
	row := q.db.QueryRow(ctx, insertPublishResult,
		arg.ChannelID,
		arg.IdempotencyKey,
		arg.PlatformPostID,
		arg.RawResponse,
	)
	var i PublishResult
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PostID,
		&i.IdempotencyKey,
		&i.PlatformPostID,
		&i.RawResponse,
		&i.PublishedAt,
	)
	return i, err
}
