// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelScheduledJob(ctx context.Context, id uuid.UUID) (int64, error)
	// ClaimScheduledJob atomically transitions scheduled -> publishing (counting the
	// attempt), returning the row only if the claim succeeded. A canceled/published
	// job is NOT scheduled, so it cannot be claimed — the worker then skips it.
	ClaimScheduledJob(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ConsumeEmailVerificationToken(ctx context.Context, id uuid.UUID) error
	ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error
	CountActiveChannelsForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// Jobs not yet in a terminal state, for the per-workspace queue quota.
	CountPendingJobsForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CountSmoke(ctx context.Context) (int64, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (WorkspaceMember, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostVariant(ctx context.Context, arg CreatePostVariantParams) (PostVariant, error)
	CreateScheduleSlot(ctx context.Context, arg CreateScheduleSlotParams) (ScheduleSlot, error)
	CreateScheduledJob(ctx context.Context, arg CreateScheduledJobParams) (ScheduledJob, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	// Add credits (topup/refund). The wallet row is created if missing.
	CreditWallet(ctx context.Context, arg CreditWalletParams) (Wallet, error)
	// Atomically deduct; returns no row when funds are insufficient.
	DebitWalletIfEnough(ctx context.Context, arg DebitWalletIfEnoughParams) (Wallet, error)
	DeleteChannel(ctx context.Context, id uuid.UUID) error
	DeleteChannelCredential(ctx context.Context, channelID uuid.UUID) error
	DeleteMediaAsset(ctx context.Context, id uuid.UUID) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	DeletePostVariant(ctx context.Context, id uuid.UUID) error
	DeleteScheduleSlot(ctx context.Context, id uuid.UUID) error
	DeleteVariantsForPost(ctx context.Context, postID uuid.UUID) error
	GetChannel(ctx context.Context, id uuid.UUID) (Channel, error)
	GetChannelByAccount(ctx context.Context, arg GetChannelByAccountParams) (Channel, error)
	GetChannelCredential(ctx context.Context, channelID uuid.UUID) (ChannelCredential, error)
	GetEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetLedgerEntryByRef(ctx context.Context, arg GetLedgerEntryByRefParams) (WalletLedger, error)
	GetMediaAsset(ctx context.Context, id uuid.UUID) (MediaAsset, error)
	GetMember(ctx context.Context, arg GetMemberParams) (WorkspaceMember, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPost(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostVariant(ctx context.Context, id uuid.UUID) (PostVariant, error)
	GetPublishResultByKey(ctx context.Context, idempotencyKey string) (PublishResult, error)
	GetScheduledJob(ctx context.Context, id uuid.UUID) (ScheduledJob, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVariantByPostChannel(ctx context.Context, arg GetVariantByPostChannelParams) (PostVariant, error)
	GetWalletBalance(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error)
	// Append a ledger entry. ON CONFLICT DO NOTHING + no row returned signals a
	// duplicate (webhook retry / double claim) so the caller can skip the credit.
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (WalletLedger, error)
	// Batched insert of all metrics for one poll (atomic, single round-trip).
	InsertMetricSnapshots(ctx context.Context, arg []InsertMetricSnapshotsParams) (int64, error)
	InsertPublishResult(ctx context.Context, arg InsertPublishResultParams) (PublishResult, error)
	// Trivial query proving the sqlc generation chain works. Replaced by real
	// domain queries from Phase 2 onward.
	InsertSmoke(ctx context.Context, note string) (SchemaSmoke, error)
	// The most recent value of every metric for one post, per channel it was
	// published to (workspace-scoped).
	LatestMetricsForPost(ctx context.Context, arg LatestMetricsForPostParams) ([]LatestMetricsForPostRow, error)
	// The most recent value of every metric for the N most-recently-active
	// (post, channel) pairs in the workspace. The LIMIT is applied in SQL (by
	// recency) so a large workspace never materializes its whole history.
	LatestMetricsForWorkspace(ctx context.Context, arg LatestMetricsForWorkspaceParams) ([]LatestMetricsForWorkspaceRow, error)
	ListAuditLogByWorkspace(ctx context.Context, arg ListAuditLogByWorkspaceParams) ([]AuditLog, error)
	ListChannels(ctx context.Context, workspaceID uuid.UUID) ([]Channel, error)
	ListChannelsDueForRefresh(ctx context.Context, arg ListChannelsDueForRefreshParams) ([]ListChannelsDueForRefreshRow, error)
	ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]WalletLedger, error)
	ListMediaAssets(ctx context.Context, arg ListMediaAssetsParams) ([]MediaAsset, error)
	ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceMember, error)
	ListPostsByWorkspace(ctx context.Context, arg ListPostsByWorkspaceParams) ([]Post, error)
	// Published posts to poll: published within the lookback window and not polled
	// since the cutoff (dedup is per (channel, platform post) via poll-state, so a
	// collision on platform_post_id across channels can't suppress another's poll,
	// and a post marked done is excluded permanently).
	ListPostsDueForMetrics(ctx context.Context, arg ListPostsDueForMetricsParams) ([]ListPostsDueForMetricsRow, error)
	ListScheduledJobsInRange(ctx context.Context, arg ListScheduledJobsInRangeParams) ([]ScheduledJob, error)
	ListScheduledRunAtForChannel(ctx context.Context, arg ListScheduledRunAtForChannelParams) ([]pgtype.Timestamptz, error)
	ListSlotsForChannel(ctx context.Context, channelID uuid.UUID) ([]ScheduleSlot, error)
	ListVariantsByPost(ctx context.Context, postID uuid.UUID) ([]PostVariant, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error)
	// Row-locks the workspace so a quota check + media insert is serialized against
	// concurrent uploads in the same workspace (prevents TOCTOU quota overshoot).
	LockWorkspaceForUpdate(ctx context.Context, id uuid.UUID) error
	// The time series of one metric for one post on one channel within a window.
	MetricSeries(ctx context.Context, arg MetricSeriesParams) ([]MetricSeriesRow, error)
	// Retention: drop snapshots older than the cutoff to bound table growth.
	PruneSnapshotsBefore(ctx context.Context, capturedAt pgtype.Timestamptz) error
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetScheduledJobStatus(ctx context.Context, arg SetScheduledJobStatusParams) error
	SetScheduledJobTaskID(ctx context.Context, arg SetScheduledJobTaskIDParams) error
	SumMediaBytesForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	TouchPost(ctx context.Context, id uuid.UUID) error
	UpdateChannelIdentity(ctx context.Context, arg UpdateChannelIdentityParams) error
	UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) error
	UpdateMemberPermissions(ctx context.Context, arg UpdateMemberPermissionsParams) (WorkspaceMember, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) error
	UpdatePostVariant(ctx context.Context, arg UpdatePostVariantParams) (PostVariant, error)
	UpsertChannelCredential(ctx context.Context, arg UpsertChannelCredentialParams) error
	// Record a poll attempt for a (channel, platform post). done is sticky: once a
	// post is gone at the platform it stays done so it's never polled again.
	UpsertPollState(ctx context.Context, arg UpsertPollStateParams) error
	// Ensure the workspace has a wallet row and return it.
	UpsertWallet(ctx context.Context, workspaceID uuid.UUID) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
