// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountSmoke(ctx context.Context) (int64, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error)
	// Trivial query proving the sqlc generation chain works. Replaced by real
	// domain queries from Phase 2 onward.
	InsertSmoke(ctx context.Context, note string) (SchemaSmoke, error)
	ListAuditLogByWorkspace(ctx context.Context, arg ListAuditLogByWorkspaceParams) ([]AuditLog, error)
}

var _ Querier = (*Queries)(nil)
