// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scheduling.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelScheduledJob = `-- name: CancelScheduledJob :execrows
UPDATE scheduled_jobs
SET status = 'canceled', updated_at = now()
WHERE id = $1 AND status = 'scheduled'
`

func (q *Queries) CancelScheduledJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelScheduledJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimScheduledJob = `-- name: ClaimScheduledJob :one
UPDATE scheduled_jobs
SET status = 'publishing', attempts = attempts + 1, updated_at = now()
WHERE id = $1 AND status = 'scheduled'
RETURNING id
`

// ClaimScheduledJob atomically transitions scheduled -> publishing (counting the
// attempt), returning the row only if the claim succeeded. A canceled/published
// job is NOT scheduled, so it cannot be claimed — the worker then skips it.
func (q *Queries) ClaimScheduledJob(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimScheduledJob, id)
	err := row.Scan(&id)
	return id, err
}

const countPendingJobsForWorkspace = `-- name: CountPendingJobsForWorkspace :one
SELECT count(*) FROM scheduled_jobs sj
JOIN posts p ON p.id = sj.post_id
WHERE p.workspace_id = $1 AND sj.status IN ('scheduled', 'publishing')
`

// Jobs not yet in a terminal state, for the per-workspace queue quota.
func (q *Queries) CountPendingJobsForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingJobsForWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduleSlot = `-- name: CreateScheduleSlot :one
INSERT INTO schedule_slots (channel_id, day_of_week, time_of_day, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, day_of_week, time_of_day, timezone, created_at
`

type CreateScheduleSlotParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	DayOfWeek int16     `json:"day_of_week"`
	TimeOfDay string    `json:"time_of_day"`
	Timezone  string    `json:"timezone"`
}

func (q *Queries) CreateScheduleSlot(ctx context.Context, arg CreateScheduleSlotParams) (ScheduleSlot, error) {
	row := q.db.QueryRow(ctx, createScheduleSlot,
		arg.ChannelID,
		arg.DayOfWeek,
		arg.TimeOfDay,
		arg.Timezone,
	)
	var i ScheduleSlot
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DayOfWeek,
		&i.TimeOfDay,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const createScheduledJob = `-- name: CreateScheduledJob :one
INSERT INTO scheduled_jobs (post_id, channel_id, run_at, status)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, channel_id, run_at, status, attempts, last_error, asynq_task_id, created_at, updated_at
`

type CreateScheduledJobParams struct {
	PostID    uuid.UUID          `json:"post_id"`
	ChannelID uuid.UUID          `json:"channel_id"`
	RunAt     pgtype.Timestamptz `json:"run_at"`
	Status    string             `json:"status"`
}

func (q *Queries) CreateScheduledJob(ctx context.Context, arg CreateScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, createScheduledJob,
		arg.PostID,
		arg.ChannelID,
		arg.RunAt,
		arg.Status,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChannelID,
		&i.RunAt,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AsynqTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduleSlot = `-- name: DeleteScheduleSlot :exec
DELETE FROM schedule_slots
WHERE id = $1
`

func (q *Queries) DeleteScheduleSlot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleSlot, id)
	return err
}

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT id, post_id, channel_id, run_at, status, attempts, last_error, asynq_task_id, created_at, updated_at
FROM scheduled_jobs
WHERE id = $1
`

func (q *Queries) GetScheduledJob(ctx context.Context, id uuid.UUID) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getScheduledJob, id)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ChannelID,
		&i.RunAt,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AsynqTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduledJobsInRange = `-- name: ListScheduledJobsInRange :many
SELECT j.id, j.post_id, j.channel_id, j.run_at, j.status, j.attempts, j.last_error, j.asynq_task_id, j.created_at, j.updated_at
FROM scheduled_jobs j
JOIN channels c ON c.id = j.channel_id
WHERE c.workspace_id = $1 AND j.run_at >= $2 AND j.run_at < $3
ORDER BY j.run_at
`

type ListScheduledJobsInRangeParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	RunAt       pgtype.Timestamptz `json:"run_at"`
	RunAt_2     pgtype.Timestamptz `json:"run_at_2"`
}

func (q *Queries) ListScheduledJobsInRange(ctx context.Context, arg ListScheduledJobsInRangeParams) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, listScheduledJobsInRange, arg.WorkspaceID, arg.RunAt, arg.RunAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ChannelID,
			&i.RunAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.AsynqTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRunAtForChannel = `-- name: ListScheduledRunAtForChannel :many
SELECT run_at
FROM scheduled_jobs
WHERE channel_id = $1 AND status = 'scheduled' AND run_at >= $2
ORDER BY run_at
`

type ListScheduledRunAtForChannelParams struct {
	ChannelID uuid.UUID          `json:"channel_id"`
	RunAt     pgtype.Timestamptz `json:"run_at"`
}

func (q *Queries) ListScheduledRunAtForChannel(ctx context.Context, arg ListScheduledRunAtForChannelParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listScheduledRunAtForChannel, arg.ChannelID, arg.RunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Timestamptz{}
	for rows.Next() {
		var run_at pgtype.Timestamptz
		if err := rows.Scan(&run_at); err != nil {
			return nil, err
		}
		items = append(items, run_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsForChannel = `-- name: ListSlotsForChannel :many
SELECT id, channel_id, day_of_week, time_of_day, timezone, created_at
FROM schedule_slots
WHERE channel_id = $1
ORDER BY day_of_week, time_of_day
`

func (q *Queries) ListSlotsForChannel(ctx context.Context, channelID uuid.UUID) ([]ScheduleSlot, error) {
	rows, err := q.db.Query(ctx, listSlotsForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleSlot{}
	for rows.Next() {
		var i ScheduleSlot
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.DayOfWeek,
			&i.TimeOfDay,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScheduledJobStatus = `-- name: SetScheduledJobStatus :exec
UPDATE scheduled_jobs
SET status = $2, last_error = $3, attempts = attempts + $4, updated_at = now()
WHERE id = $1
`

type SetScheduledJobStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	LastError string    `json:"last_error"`
	Attempts  int32     `json:"attempts"`
}

func (q *Queries) SetScheduledJobStatus(ctx context.Context, arg SetScheduledJobStatusParams) error {
	_, err := q.db.Exec(ctx, setScheduledJobStatus,
		arg.ID,
		arg.Status,
		arg.LastError,
		arg.Attempts,
	)
	return err
}

const setScheduledJobTaskID = `-- name: SetScheduledJobTaskID :exec
UPDATE scheduled_jobs
SET asynq_task_id = $2, updated_at = now()
WHERE id = $1
`

type SetScheduledJobTaskIDParams struct {
	ID          uuid.UUID `json:"id"`
	AsynqTaskID string    `json:"asynq_task_id"`
}

func (q *Queries) SetScheduledJobTaskID(ctx context.Context, arg SetScheduledJobTaskIDParams) error {
	_, err := q.db.Exec(ctx, setScheduledJobTaskID, arg.ID, arg.AsynqTaskID)
	return err
}
