// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: smoke.sql

package sqlc

import (
	"context"
)

const countSmoke = `-- name: CountSmoke :one
SELECT count(*) FROM schema_smoke
`

func (q *Queries) CountSmoke(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSmoke)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSmoke = `-- name: InsertSmoke :one

INSERT INTO schema_smoke (note)
VALUES ($1)
RETURNING id, note, created_at
`

// Trivial query proving the sqlc generation chain works. Replaced by real
// domain queries from Phase 2 onward.
func (q *Queries) InsertSmoke(ctx context.Context, note string) (SchemaSmoke, error) {
	row := q.db.QueryRow(ctx, insertSmoke, note)
	var i SchemaSmoke
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}
