// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO workspace_members (workspace_id, user_id, role, permissions)
VALUES ($1, $2, $3, $4)
RETURNING workspace_id, user_id, role, permissions, created_at, channel_restricted
`

type CreateMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Permissions []string  `json:"permissions"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.Permissions,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.ChannelRestricted,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, owner_user_id)
VALUES ($1, $2)
RETURNING id, name, owner_user_id, plan, created_at
`

type CreateWorkspaceParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.OwnerUserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT workspace_id, user_id, role, permissions, created_at, channel_restricted
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.ChannelRestricted,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT workspace_id, user_id, role, permissions, created_at, channel_restricted
FROM workspace_members
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMember{}
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.Permissions,
			&i.CreatedAt,
			&i.ChannelRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.owner_user_id, w.plan, w.created_at
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.Plan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberPermissions = `-- name: UpdateMemberPermissions :one
UPDATE workspace_members
SET role = $3, permissions = $4
WHERE workspace_id = $1 AND user_id = $2
RETURNING workspace_id, user_id, role, permissions, created_at, channel_restricted
`

type UpdateMemberPermissionsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Permissions []string  `json:"permissions"`
}

func (q *Queries) UpdateMemberPermissions(ctx context.Context, arg UpdateMemberPermissionsParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateMemberPermissions,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.Permissions,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.ChannelRestricted,
	)
	return i, err
}
